#version 450
layout(local_size_x = 4 , local_size_y=4, local_size_z = 4) in;
layout(binding = 0) uniform sampler3D in_sampler;
layout(binding = 1) writeonly buffer d_out{
	uint d_output[];
};
layout(binding = 2) uniform MetaInfo{
	uint x;
	uint y;
	uint z;
	float isovalue;
}meta;

void main(){
	uvec3 pos = gl_WorkGroupID * gl_WorkGroupSize + gl_LocalInvocationID;
	uint idx = pos.x + pos.y * meta.x + pos.z*meta.x*meta.y;
	vec3 dim = vec3(meta.x , meta.y, meta.z);
	if(idx >= meta.x * meta.y * meta.z) return;
	idx = idx*3;
	float iso = meta.isovalue;
	bool vol = texture(in_sampler, vec3(pos)/dim).x > iso;
	d_output[idx+0] = uint(vol  ^^  (texture(in_sampler, vec3(pos + uvec3(1,0,0))/dim).x > iso) );
	d_output[idx+1] = uint(vol  ^^  (texture(in_sampler, vec3(pos + uvec3(0,1,0))/dim).x > iso) );
	d_output[idx+2] = uint(vol  ^^  (texture(in_sampler, vec3(pos + uvec3(0,0,1))/dim).x > iso) );
}
