#version 450
layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) buffer Source{
	ivec4 dst[];
};

layout(binding = 1) buffer GroupSum{
	int group_sum[];
};

void main(){
	//uint tid = gl_GlobalInvocationID.x;
    uint tid = gl_WorkGroupSize.x * gl_WorkGroupID.x + gl_LocalInvocationID.x;
	uint grp_id = gl_WorkGroupID.x;
	if(grp_id != 0){
		ivec4 data = dst[tid];
		data += ivec4(group_sum[grp_id]);
		dst[tid] = data;
	}
}
